Pretraining  
a. Using distilgpt for textgeneration

b. Chat generation using mistralai/Mistral-7B-Instruct-v0.2

c. Summarize text using T5-small

In [ ]:
# ===========================================
# a.Using distilgpt2 for Text Generation
# ===========================================
!pip install -q transformers datasets evaluate accelerate sentencepiece
!pip install -q torch

import torch
from transformers import pipeline, AutoModelForCausalLM, AutoTokenizer
print("✅ Environment ready. Torch version:", torch.__version__)
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

prompt = "Artificial intelligence is transforming the world because"
inputs = tokenizer(prompt, return_tensors="pt")

outputs = model.generate(
    **inputs,
    max_length=60,
    num_return_sequences=3,
    temperature=0.8,
    top_k=50,
    top_p=0.95,
    do_sample=True
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.1 MB/s eta 0:00:00
✅ Environment ready. Torch version: 2.8.0+cu126

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [ ]:
for i, output in enumerate(outputs):
    print(f"\n--- Generated Text {i+1} ---\n")
    print(tokenizer.decode(output, skip_special_tokens=True))

--- Generated Text 1 ---

Artificial intelligence is transforming the world because the technology is moving us closer to the natural world, not closer to the natural world. Now that we have the ability to do this, we can create a new kind of self-driving car. The car will be a hybrid car that will feature a 3

--- Generated Text 2 ---

Artificial intelligence is transforming the world because of advances in the development of artificial intelligence, but it's still not new. A new study from the National Center for Artificial Intelligence, a research group at the University of Minnesota, has shown that artificial intelligence can help solve many problems.






--- Generated Text 3 ---

Artificial intelligence is transforming the world because it's the kind of place where humans can communicate with each other.

In [ ]:
# ====================================================
# b. Chat Generation using mistralai/Mistral-7B-Instruct-v0.2
# ====================================================

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

model_id = "mistralai/Mistral-7B-Instruct-v0.2"
pipe = pipeline("text-generation", model=model_id, torch_dtype=torch.bfloat16, device_map="auto")

prompt = "You are a helpful assistant. User: What is quantum computing? Assistant:"

result = pipe(prompt, max_new_tokens=120, temperature=0.7)

config.json:   0%|          | 0.00/596 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/4.54G [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.94G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu.

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

Device set to use cuda:0
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

In [ ]:
print(result[0]['generated_text'])

You are a helpful assistant. User: What is quantum computing? Assistant: Quantum computing is a type of computing technology that utilizes quantum bits, or qubits, instead of the traditional binary bits used in classical computing. Qubits can exist in multiple states at once, thanks to a property called superposition, and can also be entangled with each other, meaning the state of one qubit can depend on the state of another, no matter the distance between them. These unique properties allow quantum computers to process certain types of information much faster than classical computers for specific tasks. However, it's important to note that quantum computing is still in its infancy and

In [ ]:
# ======================================
# c. Summarize text using T5-small
# ======================================

from transformers import pipeline

summarizer = pipeline("summarization", model="t5-small")

text = """
Artificial Intelligence (AI) is a field of computer science that aims to create machines
that can perform tasks that would normally require human intelligence. This includes
learning, reasoning, problem-solving, perception, and language understanding.
"""

summary = summarizer(text, max_length=50, min_length=20, do_sample=False)

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

Device set to use cuda:0
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
print(" Summary:", summary[0]['summary_text'])

 Summary: artificial intelligence is a field of computer science that aims to create machines that can perform tasks that would normally require human intelligence . this includes learning, reasoning, problem-solving, perception, and language understanding .

 Fine-tunning

a. Using BERT(BERT-base) for sentiment analysis using IMDb sentiment
dataset  

i. Using bert-base-uncased

ii. Using Hugging Face Trainer API

In [ ]:
# Install required libraries
!pip install -q transformers datasets accelerate evaluate

# Import necessary modules
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import numpy as np
import evaluate

# Load the IMDb dataset
dataset = load_dataset("imdb")

# Load the BERT tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

# Tokenization function
def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=512)

# Tokenize datasets
tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Use small subsets for fast training
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(200))

# Load model
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

# Training arguments (fixed: use 'eval_strategy' instead of 'evaluation_strategy')
training_args = TrainingArguments(
    output_dir="bert_imdb_trainer",
    eval_strategy="epoch",           # Fixed: was 'evaluation_strategy'
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_dir="logs",
    logging_steps=10,
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
)

# Load accuracy metric
metric = evaluate.load("accuracy")

# Compute metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    compute_metrics=compute_metrics,
)

# Train
trainer.train()

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Downloading builder script: 0.00B [00:00, ?B/s]

TrainOutput(global_step=125, training_loss=0.47686387634277344, metrics={'train_runtime': 57.3598, 'train_samples_per_second': 17.434, 'train_steps_per_second': 2.179, 'total_flos': 263111055360000.0, 'train_loss': 0.47686387634277344, 'epoch': 1.0})

In [ ]:
import torch

# Sample inference with proper device handling
text = "This is a fantastic movie with great acting!"
inputs = tokenizer(text, return_tensors="pt", padding=True, truncation=True, max_length=512)

# Move inputs to the same device as the model
device = model.device  # Automatically detects GPU if available
inputs = {k: v.to(device) for k, v in inputs.items()}

# Forward pass
with torch.no_grad():
    outputs = model(**inputs)

# Get prediction
logits = outputs.logits
prediction = torch.argmax(logits, dim=-1).item()

print("Text:", text)
print("Sentiment:", "Positive" if prediction == 1 else "Negative")

Text: This is a fantastic movie with great acting!
Sentiment: Positive

b. Fine-tuning GPT for summarization.

i. Using gpt2 for text summarization using DailyMail/XSum dataset

ii. Using Hugging face Pipeline

In [ ]:
!pip install -U transformers datasets accelerate sentencepiece -q

import os
os.environ["WANDB_DISABLED"] = "true"

from datasets import load_dataset
from transformers import AutoTokenizer, GPT2LMHeadModel
from transformers import DataCollatorForLanguageModeling, TrainingArguments, Trainer
from transformers import pipeline

dataset = load_dataset("cnn_dailymail", "3.0.0")["train"].select(range(500))

tokenizer = AutoTokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained("gpt2")

def preprocess(b):
    t = ["summarize: " + x for x in b["article"]]
    return tokenizer(t, truncation=True, padding="max_length", max_length=256)

tokenized = dataset.map(preprocess, batched=True, remove_columns=["article","highlights"])
collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

args = TrainingArguments(
    output_dir="./gpt2-sum",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    num_train_epochs=1,
    learning_rate=5e-5,
    logging_steps=50,
    fp16=True
)

trainer = Trainer(model=model, args=args, train_dataset=tokenized, data_collator=collator)
trainer.train()

README.md: 0.00B [00:00, ?B/s]

3.0.0/train-00000-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00001-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00002-of-00003.parquet:   0%|          | 0.00/259M [00:00<?, ?B/s]

3.0.0/validation-00000-of-00001.parquet:   0%|          | 0.00/34.7M [00:00<?, ?B/s]

3.0.0/test-00000-of-00001.parquet:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

TrainOutput(global_step=63, training_loss=3.062107267833891, metrics={'train_runtime': 47.3863, 'train_samples_per_second': 10.552, 'train_steps_per_second': 1.329, 'total_flos': 65323008000000.0, 'train_loss': 3.062107267833891, 'epoch': 1.0})

In [ ]:
summarizer = pipeline("text-generation", model=model, tokenizer=tokenizer, max_new_tokens=60)
print(summarizer("summarize: The Eiffel Tower is visited by millions every year.")[0]["generated_text"])

Device set to use cuda:0

summarize: The Eiffel Tower is visited by millions every year. But for the second year running, the hotel's owners are making it back to normal. The two-story building, which had been destroyed by fire, is now being rebuilt by the developers of the East Village. The New York Times reports that the building has been moved to an abandoned warehouse. The

In [ ]:
# Install required libraries
!pip install -q transformers datasets accelerate evaluate

# Import modules
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import numpy as np
import evaluate
import torch

# Load IMDb dataset
dataset = load_dataset("imdb")

# Load DistilBERT tokenizer
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

# Tokenization function
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=512)

# Tokenize datasets
tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Small subsets for quick training
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(200))

# Load DistilBERT model for classification
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)

# Training arguments
training_args = TrainingArguments(
    output_dir="distilbert_imdb",
    eval_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=16,   # DistilBERT is lighter → can use larger batch
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_dir="logs",
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none",  # Disable wandb
)

# Accuracy metric
metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    compute_metrics=compute_metrics,
)

# Train
trainer.train()

# Move model to correct device for inference
model = model.to('cuda' if torch.cuda.is_available() else 'cpu')

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
text = "This is a fantastic movie with great acting!"
inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=512)
inputs = {k: v.to(model.device) for k, v in inputs.items()}

with torch.no_grad():
    outputs = model(**inputs)
    pred = torch.argmax(outputs.logits, dim=-1).item()

print("Text:", text)
print("Sentiment:", "Positive" if pred == 1 else "Negative")

Text: This is a fantastic movie with great acting!
Sentiment: Positive

For text summarization
Swap the models (bart-large-cnn, t5-small, pegasus-xsum) and change
parameters and use trainer API

In [ ]:
# Install required libraries
!pip install -q transformers datasets evaluate rouge_score accelerate torch

import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq
import numpy as np
import evaluate

# === CONFIG: 3 MODELS ===
models_to_train = [
    {"name": "facebook/bart-large-cnn", "batch_size": 4,  "epochs": 1, "prefix": ""},
    {"name": "t5-small",                "batch_size": 8,  "epochs": 1, "prefix": "summarize: "},
    {"name": "google/pegasus-xsum",     "batch_size": 4,  "epochs": 1, "prefix": ""}
]

# Load CNN/DailyMail dataset
dataset = load_dataset("cnn_dailymail", "3.0.0")
train_dataset = dataset["train"].shuffle(seed=42).select(range(1000))
eval_dataset = dataset["validation"].shuffle(seed=42).select(range(200))

# Load ROUGE
rouge = evaluate.load("rouge")

def compute_metrics(eval_pred):
    preds, labels = eval_pred
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
    result = rouge.compute(predictions=decoded_preds, references=decoded_labels, use_stemmer=True)
    return {k: round(v, 4) for k, v in result.items()}

# === TRAINING LOOP ===
for idx, config in enumerate(models_to_train):
    print(f"\n{'='*70}")
    print(f"TRAINING MODEL {idx+1}/3: {config['name']}")
    print(f"{'='*70}\n")

    MODEL_NAME = config["name"]
    BATCH_SIZE = config["batch_size"]
    EPOCHS = config["epochs"]
    PREFIX = config["prefix"]

    # Load tokenizer & model
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

    # Preprocess function
    def preprocess(examples):
        inputs = [PREFIX + doc for doc in examples["article"]]
        model_inputs = tokenizer(inputs, max_length=512, truncation=True, padding="max_length")
        with tokenizer.as_target_tokenizer():
            labels = tokenizer(examples["highlights"], max_length=128, truncation=True, padding="max_length")
        model_inputs["labels"] = labels["input_ids"]
        return model_inputs

    # Tokenize
    tokenized_train = train_dataset.map(preprocess, batched=True, remove_columns=["article", "highlights", "id"])
    tokenized_eval = eval_dataset.map(preprocess, batched=True, remove_columns=["article", "highlights", "id"])

    data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

    # Training args
    training_args = Seq2SeqTrainingArguments(
        output_dir=f"./cnn_model_{idx}_{MODEL_NAME.split('/')[-1]}",
        eval_strategy="epoch",
        save_strategy="epoch",
        per_device_train_batch_size=BATCH_SIZE,
        per_device_eval_batch_size=BATCH_SIZE,
        num_train_epochs=EPOCHS,
        weight_decay=0.01,
        predict_with_generate=True,
        fp16=torch.cuda.is_available(),
        logging_steps=10,
        load_best_model_at_end=True,
        metric_for_best_model="rouge1",
        report_to="none",
        disable_tqdm=True,
    )

    # Trainer
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_eval,
        tokenizer=tokenizer,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    # Train
    trainer.train()

    # Save
    save_dir = f"./trained_cnn_{MODEL_NAME.split('/')[-1]}"
    model.save_pretrained(save_dir)
    tokenizer.save_pretrained(save_dir)
    print(f"Model saved to: {save_dir}\n")

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 1.8 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

3.0.0/train-00000-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00001-of-00003.parquet:   0%|          | 0.00/257M [00:00<?, ?B/s]

3.0.0/train-00002-of-00003.parquet:   0%|          | 0.00/259M [00:00<?, ?B/s]

3.0.0/validation-00000-of-00001.parquet:   0%|          | 0.00/34.7M [00:00<?, ?B/s]

3.0.0/test-00000-of-00001.parquet:   0%|          | 0.00/30.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/287113 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/13368 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/11490 [00:00<?, ? examples/s]

Downloading builder script: 0.00B [00:00, ?B/s]

======================================================================
TRAINING MODEL 1/3: facebook/bart-large-cnn
======================================================================

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4034: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

/tmp/ipython-input-1606582528.py:82: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

{'loss': 4.7737, 'grad_norm': 26.25809669494629, 'learning_rate': 4.82e-05, 'epoch': 0.04}
{'loss': 1.8551, 'grad_norm': 20.00099754333496, 'learning_rate': 4.6200000000000005e-05, 'epoch': 0.08}
{'loss': 1.0938, 'grad_norm': 7.115571022033691, 'learning_rate': 4.4200000000000004e-05, 'epoch': 0.12}
{'loss': 0.9643, 'grad_norm': 5.555645942687988, 'learning_rate': 4.22e-05, 'epoch': 0.16}
{'loss': 0.9362, 'grad_norm': 5.1031317710876465, 'learning_rate': 4.02e-05, 'epoch': 0.2}
{'loss': 0.9371, 'grad_norm': 3.6869611740112305, 'learning_rate': 3.82e-05, 'epoch': 0.24}
{'loss': 0.7834, 'grad_norm': 2.7515366077423096, 'learning_rate': 3.62e-05, 'epoch': 0.28}
{'loss': 0.7989, 'grad_norm': 4.570125102996826, 'learning_rate': 3.4200000000000005e-05, 'epoch': 0.32}
{'loss': 0.8354, 'grad_norm': 4.530107498168945, 'learning_rate': 3.2200000000000003e-05, 'epoch': 0.36}
{'loss': 0.7967, 'grad_norm': 4.29384708404541, 'learning_rate': 3.02e-05, 'epoch': 0.4}
{'loss': 0.8462, 'grad_norm': 5.188340663909912, 'learning_rate': 2.8199999999999998e-05, 'epoch': 0.44}
{'loss': 0.803, 'grad_norm': 4.699766635894775, 'learning_rate': 2.6200000000000003e-05, 'epoch': 0.48}
{'loss': 0.753, 'grad_norm': 2.8842687606811523, 'learning_rate': 2.4200000000000002e-05, 'epoch': 0.52}
{'loss': 0.909, 'grad_norm': 5.801119804382324, 'learning_rate': 2.22e-05, 'epoch': 0.56}
{'loss': 0.7769, 'grad_norm': 3.7848219871520996, 'learning_rate': 2.0200000000000003e-05, 'epoch': 0.6}
{'loss': 0.8248, 'grad_norm': 3.591961145401001, 'learning_rate': 1.8200000000000002e-05, 'epoch': 0.64}
{'loss': 0.7684, 'grad_norm': 3.7461447715759277, 'learning_rate': 1.62e-05, 'epoch': 0.68}
{'loss': 0.8502, 'grad_norm': 4.751353740692139, 'learning_rate': 1.42e-05, 'epoch': 0.72}
{'loss': 0.7969, 'grad_norm': 4.418627738952637, 'learning_rate': 1.22e-05, 'epoch': 0.76}
{'loss': 0.7024, 'grad_norm': 4.568508625030518, 'learning_rate': 1.02e-05, 'epoch': 0.8}
{'loss': 0.8155, 'grad_norm': 4.580101490020752, 'learning_rate': 8.200000000000001e-06, 'epoch': 0.84}
{'loss': 0.7914, 'grad_norm': 2.998631477355957, 'learning_rate': 6.2e-06, 'epoch': 0.88}
{'loss': 0.8214, 'grad_norm': 3.7671191692352295, 'learning_rate': 4.2000000000000004e-06, 'epoch': 0.92}
{'loss': 0.7217, 'grad_norm': 4.402873992919922, 'learning_rate': 2.2e-06, 'epoch': 0.96}
{'loss': 0.7202, 'grad_norm': 3.602414846420288, 'learning_rate': 2.0000000000000002e-07, 'epoch': 1.0}
{'eval_loss': 0.9344005584716797, 'eval_rouge1': 0.4485, 'eval_rouge2': 0.2138, 'eval_rougeL': 0.3045, 'eval_rougeLsum': 0.419, 'eval_runtime': 191.7449, 'eval_samples_per_second': 1.043, 'eval_steps_per_second': 0.261, 'epoch': 1.0}

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3918: UserWarning: Moving the following attributes in the config to the generation config: {'max_length': 142, 'min_length': 56, 'early_stopping': True, 'num_beams': 4, 'length_penalty': 2.0, 'no_repeat_ngram_size': 3, 'forced_bos_token_id': 0}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(
There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

{'train_runtime': 429.0665, 'train_samples_per_second': 2.331, 'train_steps_per_second': 0.583, 'train_loss': 1.0270241775512696, 'epoch': 1.0}
Model saved to: ./trained_cnn_bart-large-cnn


======================================================================
TRAINING MODEL 2/3: t5-small
======================================================================

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4034: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

/tmp/ipython-input-1606582528.py:82: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

{'loss': 8.8017, 'grad_norm': nan, 'learning_rate': 4.64e-05, 'epoch': 0.08}
{'loss': 6.3545, 'grad_norm': 39.378238677978516, 'learning_rate': 4.24e-05, 'epoch': 0.16}
{'loss': 3.9505, 'grad_norm': 17.64763069152832, 'learning_rate': 3.8400000000000005e-05, 'epoch': 0.24}
{'loss': 2.6287, 'grad_norm': 12.724783897399902, 'learning_rate': 3.4399999999999996e-05, 'epoch': 0.32}
{'loss': 2.0774, 'grad_norm': 3.3072240352630615, 'learning_rate': 3.04e-05, 'epoch': 0.4}
{'loss': 1.9239, 'grad_norm': 2.6248679161071777, 'learning_rate': 2.64e-05, 'epoch': 0.48}
{'loss': 1.8721, 'grad_norm': 2.5574939250946045, 'learning_rate': 2.2400000000000002e-05, 'epoch': 0.56}
{'loss': 1.7039, 'grad_norm': 1.9652395248413086, 'learning_rate': 1.84e-05, 'epoch': 0.64}
{'loss': 1.6885, 'grad_norm': 3.360652208328247, 'learning_rate': 1.44e-05, 'epoch': 0.72}
{'loss': 1.5887, 'grad_norm': 3.866903305053711, 'learning_rate': 1.04e-05, 'epoch': 0.8}
{'loss': 1.6334, 'grad_norm': 1.8036472797393799, 'learning_rate': 6.4000000000000006e-06, 'epoch': 0.88}
{'loss': 1.5282, 'grad_norm': 1.9898815155029297, 'learning_rate': 2.4000000000000003e-06, 'epoch': 0.96}
{'eval_loss': 1.3650412559509277, 'eval_rouge1': 0.0025, 'eval_rouge2': 0.0025, 'eval_rougeL': 0.0025, 'eval_rougeLsum': 0.0025, 'eval_runtime': 10.9187, 'eval_samples_per_second': 18.317, 'eval_steps_per_second': 2.29, 'epoch': 1.0}

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

{'train_runtime': 62.7904, 'train_samples_per_second': 15.926, 'train_steps_per_second': 1.991, 'train_loss': 2.9201814956665038, 'epoch': 1.0}
Model saved to: ./trained_cnn_t5-small


======================================================================
TRAINING MODEL 3/3: google/pegasus-xsum
======================================================================

tokenizer_config.json:   0%|          | 0.00/87.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-xsum and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

generation_config.json:   0%|          | 0.00/259 [00:00<?, ?B/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py:4034: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

/tmp/ipython-input-1606582528.py:82: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

{'loss': 7.2589, 'grad_norm': 11.655848503112793, 'learning_rate': 4.82e-05, 'epoch': 0.04}
{'loss': 7.5261, 'grad_norm': 10.25871467590332, 'learning_rate': 4.6200000000000005e-05, 'epoch': 0.08}
{'loss': 7.0483, 'grad_norm': 9.553303718566895, 'learning_rate': 4.4200000000000004e-05, 'epoch': 0.12}
{'loss': 6.7442, 'grad_norm': 7.55605936050415, 'learning_rate': 4.22e-05, 'epoch': 0.16}
{'loss': 6.7151, 'grad_norm': 6.712576866149902, 'learning_rate': 4.02e-05, 'epoch': 0.2}
{'loss': 6.5959, 'grad_norm': 5.302306652069092, 'learning_rate': 3.82e-05, 'epoch': 0.24}
{'loss': 6.8034, 'grad_norm': 17.688039779663086, 'learning_rate': 3.62e-05, 'epoch': 0.28}
{'loss': 6.5117, 'grad_norm': 3.981358051300049, 'learning_rate': 3.4200000000000005e-05, 'epoch': 0.32}
{'loss': 6.324, 'grad_norm': 4.776278495788574, 'learning_rate': 3.2200000000000003e-05, 'epoch': 0.36}
{'loss': 6.3659, 'grad_norm': 14.402203559875488, 'learning_rate': 3.02e-05, 'epoch': 0.4}
{'loss': 6.011, 'grad_norm': 4.017072677612305, 'learning_rate': 2.8199999999999998e-05, 'epoch': 0.44}
{'loss': 6.3792, 'grad_norm': 3.6542537212371826, 'learning_rate': 2.6200000000000003e-05, 'epoch': 0.48}
{'loss': 6.2583, 'grad_norm': 5.960478782653809, 'learning_rate': 2.4200000000000002e-05, 'epoch': 0.52}
{'loss': 5.6596, 'grad_norm': 4.050637245178223, 'learning_rate': 2.22e-05, 'epoch': 0.56}
{'loss': 6.2725, 'grad_norm': 3.975100517272949, 'learning_rate': 2.0200000000000003e-05, 'epoch': 0.6}
{'loss': 5.9337, 'grad_norm': 26.69715690612793, 'learning_rate': 1.8200000000000002e-05, 'epoch': 0.64}
{'loss': 6.2875, 'grad_norm': 3.8825278282165527, 'learning_rate': 1.62e-05, 'epoch': 0.68}
{'loss': 6.0021, 'grad_norm': 8.836891174316406, 'learning_rate': 1.42e-05, 'epoch': 0.72}
{'loss': 6.0191, 'grad_norm': 5.367282867431641, 'learning_rate': 1.22e-05, 'epoch': 0.76}
{'loss': 6.4708, 'grad_norm': 9.822832107543945, 'learning_rate': 1.02e-05, 'epoch': 0.8}
{'loss': 5.8549, 'grad_norm': 9.680572509765625, 'learning_rate': 8.200000000000001e-06, 'epoch': 0.84}
{'loss': 6.1309, 'grad_norm': 5.5366926193237305, 'learning_rate': 6.2e-06, 'epoch': 0.88}
{'loss': 6.2346, 'grad_norm': 43.249122619628906, 'learning_rate': 4.2000000000000004e-06, 'epoch': 0.92}
{'loss': 6.0926, 'grad_norm': 11.638588905334473, 'learning_rate': 2.2e-06, 'epoch': 0.96}
{'loss': 6.0171, 'grad_norm': 4.910899639129639, 'learning_rate': 2.0000000000000002e-07, 'epoch': 1.0}
{'eval_loss': 5.269283294677734, 'eval_rouge1': 0.36, 'eval_rouge2': 0.1627, 'eval_rougeL': 0.2539, 'eval_rougeLsum': 0.2541, 'eval_runtime': 158.3764, 'eval_samples_per_second': 1.263, 'eval_steps_per_second': 0.316, 'epoch': 1.0}

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3918: UserWarning: Moving the following attributes in the config to the generation config: {'max_length': 64, 'num_beams': 8, 'length_penalty': 0.6}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(
There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

{'train_runtime': 627.1865, 'train_samples_per_second': 1.594, 'train_steps_per_second': 0.399, 'train_loss': 6.380697540283203, 'epoch': 1.0}
Model saved to: ./trained_cnn_pegasus-xsum

In [ ]:
from transformers import pipeline
import torch, os, warnings, textwrap

# Hide all warnings
warnings.filterwarnings("ignore")
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# Test article
text = """London (CNN) -- A British man has been charged with murder after his wife and daughter were found dead at their home in southern England, police said Tuesday.
The bodies of 43-year-old Samantha Baldwin and her 7-year-old daughter, Lily, were discovered Monday at their home in Basingstoke, Hampshire, Hampshire Constabulary said.
The suspect, 45-year-old David Baldwin, was arrested at the scene and remains in custody, police said. He is due to appear in court Wednesday.
A post-mortem examination is being carried out to establish the cause of death, police said. Neighbors described the family as "quiet and private." """

# Your actual saved model folders
models = [
    ("BART-Large-CNN",   "/content/trained_cnn_bart-large-cnn"),
    ("T5-Small",         "/content/trained_cnn_t5-small"),
    ("Pegasus-XSum",     "/content/trained_cnn_pegasus-xsum")
]

print("=" * 90)
print("CNN/DAILYMAIL SUMMARIZATION RESULTS".center(90))
print("=" * 90 + "\n")

for name, folder in models:
    if not os.path.exists(folder):
        print(f"ERROR: Folder not found → {folder}")
        print("   Make sure the model was saved correctly.\n")
        continue

    summarizer = pipeline(
        "summarization",
        model=folder,
        tokenizer=folder,
        device=0 if torch.cuda.is_available() else -1,
        max_length=80,
        min_length=30,
        do_sample=False,
        truncation=True,
        clean_up_tokenization_spaces=True
    )

    summary = summarizer(text)[0]["summary_text"]

    print(f"{name.upper()}")
    print("—" * 70)
    print(textwrap.fill(summary, width=88))
    print()

==========================================================================================
                           CNN/DAILYMAIL SUMMARIZATION RESULTS
==========================================================================================

Device set to use cuda:0
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

BART-LARGE-CNN
——————————————————————————————————————————————————————————————————————
Samantha Baldwin, 43, and her 7-year-old daughter, Lily, were found dead at their home.
David Baldwin, 45, was arrested at the scene and remains in custody, police say. A post-
mortem examination is being carried out to establish the cause of death.

Device set to use cuda:0
Your max_length is set to 200, but your input_length is only 148. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=74)

T5-SMALL
——————————————————————————————————————————————————————————————————————
the bodies of Samantha Baldwin, 43, and her 7-year-old daughter, Lily, were found Monday
at their home in southern England. David Baldwin, 45, was arrested at the scene and
remains in custody, police say. Neighbors described the family as "quiet and private"

Device set to use cuda:0

PEGASUS-XSUM
——————————————————————————————————————————————————————————————————————
The bodies of 43-year-old Samantha Baldwin and her 7-year-old daughter, Lily, were
discovered Monday at their home in Basingstoke, Hampshire, police said.

For Question Answering Use RoBERTa variants, GPT-3/4 fine-tuned on SQuAD
dataset

In [ ]:
!pip install -q transformers datasets accelerate sentencepiece

from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForQuestionAnswering
from transformers import TrainingArguments, Trainer, DefaultDataCollator
import torch
import os

os.environ["WANDB_DISABLED"] = "true"

dataset = load_dataset("squad")

tokenizer = AutoTokenizer.from_pretrained("roberta-base")
model = AutoModelForQuestionAnswering.from_pretrained("roberta-base")

def preprocess(example):
    inputs = tokenizer(
        example["question"],
        example["context"],
        max_length=384,
        truncation=True,
        padding="max_length",
        return_offsets_mapping=True
    )
    offset = inputs["offset_mapping"]
    answers = example["answers"]["text"][0]
    start_char = example["answers"]["answer_start"][0]
    end_char = start_char + len(answers)

    start_pos = 0
    end_pos = 0
    for i, (s, e) in enumerate(offset):
        if s <= start_char < e:
            start_pos = i
        if s < end_char <= e:
            end_pos = i

    inputs["start_positions"] = start_pos
    inputs["end_positions"] = end_pos
    inputs.pop("offset_mapping")
    return inputs

tokenized = dataset.map(preprocess, batched=False)

collator = DefaultDataCollator()

args = TrainingArguments(
    output_dir="./roberta-qa",
    per_device_train_batch_size=8,
    num_train_epochs=1,
    logging_steps=100,
    report_to=[]
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized["train"],
    eval_dataset=tokenized["validation"],
    data_collator=collator,
    tokenizer=tokenizer
)

trainer.train()

from transformers import pipeline
qa = pipeline("question-answering", model=model, tokenizer=tokenizer)

Some weights of RobertaForQuestionAnswering were not initialized from the model checkpoint at roberta-base and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/87599 [00:00<?, ? examples/s]

Map:   0%|          | 0/10570 [00:00<?, ? examples/s]

Device set to use cuda:0

In [ ]:
print(qa({"question":"Who founded Microsoft?", "context":"Microsoft was founded by Bill Gates and Paul Allen."}))

{'score': 0.8770565986633301, 'start': 25, 'end': 50, 'answer': 'Bill Gates and Paul Allen'}

Build a simple rule-based chatbot for FAQs.

In [ ]:
def chatbot(message):
    msg = message.lower()

    # Greetings
    if "hello" in msg or "hi" in msg:
        return "Hello! How can I help you today?"

    # About company
    elif "what is your name" in msg:
        return "I'm a simple FAQ chatbot."

    elif "what do you do" in msg:
        return "I answer frequently asked questions."

    # Timings
    elif "working hours" in msg or "open" in msg:
        return "We are open from 9 AM to 6 PM, Monday to Saturday."

    # Pricing
    elif "price" in msg or "cost" in msg:
        return "Pricing depends on the service. Basic plans start at $10/month."

    # Support
    elif "support" in msg or "help" in msg:
        return "You can contact support at support@example.com."

    # Location
    elif "location" in msg or "where are you" in msg:
        return "We are located in Chennai, India."

    # Goodbye
    elif "bye" in msg or "goodbye" in msg:
        return "Goodbye! Have a great day!"

    # Default fallback
    else:
        return "I'm not sure about that. Could you ask something else?"


# Chat loop
print("Type 'exit' to stop.\n")
while True:
    user = input("You: ")
    if user.lower() == "exit":
        print("Chatbot: Goodbye!")
        break
    print("Chatbot:", chatbot(user))

Type 'exit' to stop.

You: support
Chatbot: You can contact support at support@example.com.
You: bye
Chatbot: Goodbye! Have a great day!
You: exit
Chatbot: Goodbye!

Apply various prompting techniques and view the difference

In [ ]:
!pip install transformers accelerate sentencepiece -q

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline

model = "google/flan-t5-large"  # fits on Colab T4 with 16GB
pipe = pipeline("text2text-generation", model=model, tokenizer=model, max_new_tokens=150)

def run(prompt):
    print("\n--- PROMPT ---")
    print(prompt)
    print("--- OUTPUT ---")
    print(pipe(prompt)[0]["generated_text"])
    print("\n")

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.13G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [ ]:


# 1. Zero-shot
run("Explain blockchain in simple terms.")

# 2. One-shot
run("""
Q: What is AI?
A: AI means machines that can think and learn like humans.

Q: What is blockchain?
A:
""")

# 3. Few-shot
run("""
Q: What is AI?
A: AI refers to machines performing tasks that require human intelligence.

Q: What is Machine Learning?
A: ML is a subset of AI that learns patterns from data.

Q: What is blockchain?
A:
""")

# 4. Chain-of-thought
run("Why do objects fall to the ground? Let's think step by step.")

# 5. Self-consistency style
run("""
Why does ice float on water?

Let's think step by step:
""")

# 6. Instruction prompting
run("""
Summarize the following in 3 lines:
Artificial Intelligence enables machines to learn from data and make decisions.
""")

# 7. Role prompting
run("""
You are a polite science teacher.
Explain how the Internet works.
""")

# 8. Delimiter prompting
run("""
Summarize this text: <text>Machines learn patterns from data in ML.</text>
""")

# 9. Contrastive prompt
run("""
Bad summary: It's about machines.
Good summary: Give a precise, clear summary.

Text: Deep learning uses neural networks with layers to learn patterns from data.

Summary:
""")

--- PROMPT ---
Explain blockchain in simple terms.
--- OUTPUT ---
The blockchain is a digital record of transactions.



--- PROMPT ---

Q: What is AI?
A: AI means machines that can think and learn like humans.

Q: What is blockchain?
A:

--- OUTPUT ---
Blockchain () is a cryptographic protocol used to store and verify cryptographic transactions.



--- PROMPT ---

Q: What is AI?
A: AI refers to machines performing tasks that require human intelligence.

Q: What is Machine Learning?
A: ML is a subset of AI that learns patterns from data.

Q: What is blockchain?
A:

--- OUTPUT ---
Blockchain is a distributed ledger technology that uses cryptographic hashes to record transactions.



--- PROMPT ---
Why do objects fall to the ground? Let's think step by step.
--- OUTPUT ---
Objects fall to the ground when gravity pulls them down. Gravity causes objects to fall to the ground. So, the answer is gravity.



--- PROMPT ---

Why does ice float on water?

Let's think step by step:

--- OUTPUT ---
Ice is a solid. Water is a liquid. So, ice floats on water. So, the answer is because ice is a solid.



--- PROMPT ---

Summarize the following in 3 lines:
Artificial Intelligence enables machines to learn from data and make decisions.

--- OUTPUT ---
Artificial Intelligence (AI) is the process of making computers smarter.



--- PROMPT ---

You are a polite science teacher.
Explain how the Internet works.

--- OUTPUT ---
The Internet is a network of computers that communicate with each other. The computers are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The nodes are called nodes. The



--- PROMPT ---

Summarize this text: <text>Machines learn patterns from data in ML.</text>

--- OUTPUT ---
Machine learning (ML) is a branch of computer science that focuses on learning patterns from data.



--- PROMPT ---

Bad summary: It's about machines.
Good summary: Give a precise, clear summary.

Text: Deep learning uses neural networks with layers to learn patterns from data.

Summary:

--- OUTPUT ---
Deep learning uses neural networks with layers to learn patterns from data.

 Compare extractive and abstractive summarization using Hugging Face and TextRank

In [ ]:
!pip install -U transformers datasets summa -q

from summa.summarizer import summarize
from transformers import pipeline

text = """Artificial Intelligence is transforming industries across the globe.
Companies are rapidly adopting AI solutions to automate tasks, increase efficiency,
enhance customer experience, and make better decisions. The rise of AI-driven
innovation has created new opportunities in healthcare, finance, education, and transportation."""

extractive = summarize(text, ratio=0.4)

abstractive_model = pipeline("summarization", model="t5-base", tokenizer="t5-base")
abstractive = abstractive_model("summarize: " + text, max_length=60, min_length=20)[0]["summary_text"]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.9/54.9 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.6/511.6 kB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.7/47.7 MB 19.8 MB/s eta 0:00:00
  Building wheel for summa (setup.py) ... done

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

Device set to use cuda:0
Both `max_new_tokens` (=256) and `max_length`(=60) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

In [ ]:
print("Extractive Summary (TextRank):\n", extractive, "\n")
print("Abstractive Summary (HF):\n", abstractive)

Extractive Summary (TextRank):
 Companies are rapidly adopting AI solutions to automate tasks, increase efficiency,
The rise of AI-driven

Abstractive Summary (HF):
 companies are rapidly adopting AI solutions to automate tasks . the rise of AI-driven innovation has created new opportunities .

Compare retrieval-based vs generative chatbot responses.

In [ ]:
!pip install -q transformers scikit-learn

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

corpus = [
    "Hello, how can I help you?",
    "AI stands for Artificial Intelligence.",
    "Machine learning is a subset of AI.",
    "The weather is nice today.",
    "Chatbots can be retrieval-based or generative."
]

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

def retrieval_chatbot(query):
    q_vec = vectorizer.transform([query])
    sims = cosine_similarity(q_vec, X).flatten()
    return corpus[sims.argmax()]

tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-small")

def generative_chatbot(query):
    inputs = tokenizer(query, return_tensors="pt")
    output = model.generate(**inputs, max_new_tokens=50)
    return tokenizer.decode(output[0], skip_special_tokens=True)

query = "What is AI?"

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [ ]:
print("User:", query)
print("\nRetrieval-based Response:\n", retrieval_chatbot(query))
print("\nGenerative Response:\n", generative_chatbot(query))

User: What is AI?

Retrieval-based Response:
 Machine learning is a subset of AI.

Generative Response:
 AI (disambiguation) AI is a term used to describe a person's behavior.